<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.16" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
		<PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\salespoints.Application\salespoints.Application.csproj" />
	  <ProjectReference Include="..\salespoints.Infrastructure\salespoints.Infrastructure.csproj" />
	</ItemGroup>

</Project>
