<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="10.0.1" />
		<PackageReference Include="FluentValidation" Version="11.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\salespoints.Domain\salespoints.Domain.csproj" />
	  <ProjectReference Include="..\salespoints.Shared\salespoints.Shared.csproj" />
	</ItemGroup>

</Project>
